# Generated by Django 4.1.4 on 2023-01-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0002_slots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
