# Generated by Django 4.1.4 on 2023-01-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0004_booking_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
