# Generated by Django 4.1.4 on 2023-01-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0005_alter_slot_end_time_alter_slot_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='phone_user',
            field=models.CharField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='User Mail'),
        ),
    ]
