# Generated by Django 4.1.4 on 2023-01-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btbookturf', '0006_myusers_phone_user_alter_myusers_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
