# Generated by Django 4.1.4 on 2023-01-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0007_booking_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(),
        ),
    ]
