# Generated by Django 4.1.4 on 2023-03-12 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0009_alter_ground_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
