# Generated by Django 4.1.4 on 2023-03-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0010_remove_booking_slot_delete_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(default=1, max_length=20)),
                ('end_time', models.CharField(default=1, max_length=20)),
            ],
        ),
    ]
