# Generated by Django 4.1.4 on 2023-03-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0012_booking_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='manager',
        ),
    ]
