# Generated by Django 4.1.4 on 2023-07-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('btbookturf', '0018_remove_booking_attendees_delete_myusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_pk',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='members.myusers'),
        ),
    ]
