# Generated by Django 4.1.4 on 2023-07-04 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btbookturf', '0019_alter_booking_user_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_pk',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
