# Generated by Django 4.1.4 on 2023-07-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btbookturf', '0025_alter_booking_user_pk'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='user',
        ),
        migrations.AddField(
            model_name='myusers',
            name='userBooking',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='btbookturf.booking'),
        ),
    ]
