# Generated by Django 4.1.4 on 2023-07-05 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0002_remove_myusers_user_myusers_userbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='userBooking',
        ),
        migrations.AddField(
            model_name='myusers',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
