# Generated by Django 4.1.4 on 2023-07-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_myusers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusers',
            name='user',
        ),
    ]
