# Generated by Django 4.1.4 on 2023-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_myusers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='user',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
